baseURL = "https://wbatey.co/"
theme = "cocoa-eh"
languageCode = "en-us"
author = "Will Batey"
title = "Will Batey"

[params]
dateform = "27 April 2019"
description = "Will Batey"
lang = "en"
email = "w.b@use.startmail.com"
github = "wlabatey"
logofile = ""
align_left = true
share = false
disableFancyFonts = true
highlightjs = false
progressively = false
fathomurl = false
uselatex = false
googleFonts = false
homeScripts = false
githubRepo = false
gitlabRepo = false
copyright = false
RSSLink = false

[markup.goldmark.renderer]
unsafe = true
